export const SITE_NAME = 'Hotel Vatika Dhaba'
export const TAGLINE = 'Premium Pure Veg Dining with a Nature View'

export const CONTACT = {
  address: 'Hotel Vatika Dhaba\nNagpur Highway, Maharashtra, India',
  phone: '+91 9890836578',
  whatsapp: '9890836578',
  hours: '11:00 AM - 11:00 PM',
  mapsUrl: 'https://maps.app.goo.gl/X67CyikEynoZ967s5',
  mapsEmbed: 'https://www.google.com/maps?q=Hotel%20Vatika%20Dhaba%20Nagpur%20Highway&output=embed',
}

export const NAV_LINKS = [
  { label: 'Home', href: '#home' },
  { label: 'Menu', href: '#menu' },
  { label: 'Gallery', href: '#gallery' },
  { label: 'Contact', href: '#contact' },
]

export const MENU_CATEGORIES = ['All', 'Starters', 'Parathas', 'Dal', 'Sabzi', 'Paneer Special', 'Sides', 'Roti', 'Rice', 'Beverages']

export const DISHES = [
  // Starters
  {
    id: 1,
    name: 'पापड साधा',
    nameEn: 'Papad Sadha',
    price: 'Rs. 10',
    description: 'Crispy papad',
    category: 'Starters',
    image: 'https://5.imimg.com/data5/FX/VW/SO/SELLER-78728074/masala-appalam-papad-1000x1000.jpg',
  },
  {
    id: 2,
    name: 'पापड मसाला',
    nameEn: 'Papad Masala',
    price: 'Rs. 20',
    description: 'Papad topped with spices',
    category: 'Starters',
    image: 'https://images.pexels.com/photos/34347890/pexels-photo-34347890.jpeg?cs=srgb&dl=pexels-shyamsrivastava-34347890.jpg&fm=jpg',
  },
  {
    id: 3,
    name: 'पापड भुर्जी',
    nameEn: 'Papad Bhurji',
    price: 'Rs. 100',
    description: 'Crispy crushed papad with onions and spices',
    category: 'Starters',
    image: 'https://i.ytimg.com/vi/SfyrU3KflSg/maxresdefault.jpg',
  },
  {
    id: 4,
    name: 'कांदा पकोडा',
    nameEn: 'Kanda Pakoda',
    price: 'Rs. 80',
    description: 'Crispy onion fritters',
    category: 'Starters',
    image: 'https://img.freepik.com/premium-photo/crispy-kanda-bhaji-bhajji-pyaj-pakode-fried-onion-pakora-delicious-street-food-from-india_466689-73024.jpg?w=2000',
  },
  {
    id: 5,
    name: 'पनीर पकोडा',
    nameEn: 'Paneer Pakoda',
    price: 'Rs. 100',
    description: 'Crispy paneer fritters',
    category: 'Starters',
    image: 'https://i.pinimg.com/736x/6d/3c/94/6d3c94a067ad19e20b0db74bc85a720d.jpg',
  },
  // Parathas
  {
    id: 6,
    name: 'पराठा साधा',
    nameEn: 'Paratha Sadha',
    price: 'Rs. 50',
    description: 'Plain paratha',
    category: 'Parathas',
    image: 'https://img.freepik.com/premium-photo/aloo-paratha-white-background_1059083-1146.jpg',
  },
  {
    id: 7,
    name: 'पराठा मसाला',
    nameEn: 'Paratha Masala',
    price: 'Rs. 80',
    description: 'Spiced paratha',
    category: 'Parathas',
    image: 'https://tse4.mm.bing.net/th/id/OIP.H_LtSY4qc9vc_L-bgYbBAQHaE8?w=3072&h=2048&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 8,
    name: 'पराठा मसाला (घी)',
    nameEn: 'Paratha Masala (Ghee)',
    price: 'Rs. 100',
    description: 'Spiced paratha with ghee',
    category: 'Parathas',
    image: 'https://tse4.mm.bing.net/th/id/OIP.H_LtSY4qc9vc_L-bgYbBAQHaE8?w=3072&h=2048&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 9,
    name: 'पराठा पनीर',
    nameEn: 'Paratha Paneer',
    price: 'Rs. 100',
    description: 'Paneer stuffed paratha',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/12737919/pexels-photo-12737919.jpeg?cs=srgb&dl=pexels-dhiraj-jain-207743066-12737919.jpg&fm=jpg',
  },
  {
    id: 10,
    name: 'पराठा पनीर (घी)',
    nameEn: 'Paratha Paneer (Ghee)',
    price: 'Rs. 120',
    description: 'Paneer stuffed paratha with ghee',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/12737919/pexels-photo-12737919.jpeg?cs=srgb&dl=pexels-dhiraj-jain-207743066-12737919.jpg&fm=jpg',
  },
  // Dal
  {
    id: 11,
    name: 'दाल तडका',
    nameEn: 'Dal Tadka',
    price: 'Rs. 150',
    description: 'Yellow dal tempered with desi ghee and cumin',
    category: 'Dal',
    image: 'https://tse3.mm.bing.net/th/id/OIP.U0jSXW04EMGfXcnOFEtrmgHaE7?w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 12,
    name: 'दाल फ्राय',
    nameEn: 'Dal Fry',
    price: 'Rs. 140',
    description: 'Lightly tempered yellow dal',
    category: 'Dal',
    image: 'https://holycowvegan.net/wp-content/uploads/2022/09/dal-recipe-3-768x946.jpg',
  },
  {
    id: 13,
    name: 'उळदचना दाल',
    nameEn: 'Uladchana Dal',
    price: 'Rs. 140',
    description: 'Split black gram dal',
    category: 'Dal',
    image: 'https://cdn.fastpixel.io/fp/ret_img+v_c49c+w_800+h_530+q_lossless+to_webp/www.wholygoodness.com/wp-content/uploads/2024/11/Urad-Dal-Recipe-Dhaba-Style-800x530.jpg',
  },
  {
    id: 14,
    name: 'दाल मकनी',
    nameEn: 'Dal Makhani',
    price: 'Rs. 190',
    description: 'Creamy black lentils slow-cooked with butter',
    category: 'Dal',
    image: 'https://www.kuchpakrahahai.in/wp-content/uploads/2016/08/DSC_3812_WM.jpg',
  },
  // Sabzi
  {
    id: 15,
    name: 'आलू मटर',
    nameEn: 'Aloo Matar',
    price: 'Rs. 140',
    description: 'Potato and peas curry',
    category: 'Sabzi',
    image: 'https://tse1.mm.bing.net/th/id/OIP.cXP9-hpwGoENul1lmd324gHaHa?w=500&h=500&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 16,
    name: 'गोबी मसाला',
    nameEn: 'Gobi Masala',
    price: 'Rs. 140',
    description: 'Cauliflower in spiced gravy',
    category: 'Sabzi',
    image: 'https://i0.wp.com/aartimadan.com/wp-content/uploads/2020/11/gobi-aloo.jpg?resize=768%2C431&ssl=1',
  },
  {
    id: 17,
    name: 'भेंडी फ्राय',
    nameEn: 'Bhindi Fry',
    price: 'Rs. 140',
    description: 'Crispy okra fry',
    category: 'Sabzi',
    image: 'https://i.ytimg.com/vi/bS-19BSPP6Y/maxresdefault.jpg',
  },
  {
    id: 18,
    name: 'राजमा',
    nameEn: 'Rajma',
    price: 'Rs. 140',
    description: 'Kidney beans curry',
    category: 'Sabzi',
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2015/11/rajma-recipe-1.jpg',
  },
  {
    id: 19,
    name: 'चना मसाला',
    nameEn: 'Chana Masala',
    price: 'Rs. 140',
    description: 'Spiced chickpea curry',
    category: 'Sabzi',
    image: 'https://img.freepik.com/premium-photo/chana-chat-indian-chickpea-charm_960396-189003.jpg?w=996',
  },
  {
    id: 20,
    name: 'मटकी',
    nameEn: 'Matki',
    price: 'Rs. 140',
    description: 'Sprouted moth beans curry',
    category: 'Sabzi',
    image: 'https://tse2.mm.bing.net/th/id/OIP.5HHSgwhVT9b_WpOZ7IFjgQHaEA?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 21,
    name: 'कळी पकोडा',
    nameEn: 'Kali Pakoda',
    price: 'Rs. 140',
    description: 'Crispy gram flour fritters',
    category: 'Sabzi',
    image: 'https://i.ytimg.com/vi/LQ4iBAJzh3I/maxresdefault.jpg',
  },
  {
    id: 22,
    name: 'शेव भाजी',
    nameEn: 'Shev Bhaji',
    price: 'Rs. 140',
    description: 'Sev in vegetable curry',
    category: 'Sabzi',
    image: 'https://images.picxy.com/cache/2020/8/16/1d9c09b229e82486c330230e691e821d.jpg',
  },
  {
    id: 23,
    name: 'आलू जिरा',
    nameEn: 'Aloo Jira',
    price: 'Rs. 140',
    description: 'Potato tempered with cumin',
    category: 'Sabzi',
    image: 'https://static.toiimg.com/thumb/125268612.jpg?imgsize=1601144&photoid=125268612&width=600&height=335&resizemode=75',
  },
  {
    id: 24,
    name: 'टमाटर चटणी',
    nameEn: 'Tomato Chutney',
    price: 'Rs. 140',
    description: 'Spicy tomato chutney',
    category: 'Sabzi',
    image: 'https://5.imimg.com/data5/EG/UU/XP/SELLER-28418997/mixed-pickle-500x500.jpg',
  },
  {
    id: 25,
    name: 'बैंगन भरता',
    nameEn: 'Baingan Bharta',
    price: 'Rs. 140',
    description: 'Smoked eggplant mash',
    category: 'Sabzi',
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2020/09/baingan-bharta.jpg',
  },
  {
    id: 26,
    name: 'झुणका',
    nameEn: 'Zunka',
    price: 'Rs. 140',
    description: 'Traditional Maharashtrian gram flour curry',
    category: 'Sabzi',
    image: 'https://th.bing.com/th/id/R.791ddf9c8d8d7f98bb0b451c56981ac9?rik=TZiOlPoL8rVRgw&riu=http%3a%2f%2fblog.kesargrocery.com%2fwp-content%2fuploads%2f2023%2f02%2fbaigan-bharta-hindi-vangyache-bharit-marathi-is-roasted-mashed-eggplant-fry-curry-favourite-maharashtrian-menu-served-tawa-selective-focus.jpg&ehk=GdB06jW6RzsMCjCTIeuAwKVRRdQlajZVNFUeUHYYN0k%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    id: 27,
    name: 'मेथी फ्राय',
    nameEn: 'Methi Fry',
    price: 'Rs. 140',
    description: 'Fenugreek leaves fry',
    category: 'Sabzi',
    image: 'https://www.theintrepideater.com/wp-content/uploads/2023/07/DSC_0254-4.jpg',
  },
  {
    id: 28,
    name: 'करेला फ्राय',
    nameEn: 'Karela Fry',
    price: 'Rs. 140',
    description: 'Bitter gourd fry',
    category: 'Sabzi',
    image: 'https://smithakalluraya.com/wp-content/uploads/2022/08/air-fry-botter-gourd-chips.jpg',
  },
  {
    id: 29,
    name: 'पालक प्लेन',
    nameEn: 'Palak Plain',
    price: 'Rs. 150',
    description: 'Plain spinach curry',
    category: 'Sabzi',
    image: 'https://img.freepik.com/premium-photo/lasooni-palak-recipe-dhaba-style-garlic-spinach-curry-indian-main-course-served-with-naan_466689-85138.jpg',
  },
  {
    id: 30,
    name: 'ग्रेवी आलू',
    nameEn: 'Gravy Aloo',
    price: 'Rs. 150',
    description: 'Potato in rich gravy',
    category: 'Sabzi',
    image: 'https://www.lifeberrys.com/img/article/pyaz-1671791839-lb.jpg',
  },
  {
    id: 31,
    name: 'मिक्स व्हेज',
    nameEn: 'Mix Veg',
    price: 'Rs. 160',
    description: 'Seasonal vegetables in spiced tomato gravy',
    category: 'Sabzi',
    image: 'https://foodfusion.com/wp-content/uploads/2019/06/Dhabba-style-mix-sabzi-Recipe-by-Food-fusion-4.jpg',
  },
  // Paneer Special
  {
    id: 32,
    name: 'पनीर मेथी फ्राय',
    nameEn: 'Paneer Methi Fry',
    price: 'Rs. 200',
    description: 'Paneer with fenugreek leaves',
    category: 'Paneer Special',
    image: 'https://www.scrumptiously.com/wp-content/uploads/2025/01/MethiPaneer.webp',
  },
  {
    id: 33,
    name: 'पनीर बटर मसाला',
    nameEn: 'Paneer Butter Masala',
    price: 'Rs. 200',
    description: 'Paneer in rich buttery tomato gravy',
    category: 'Paneer Special',
    image: 'https://www.ruchiskitchen.com/wp-content/uploads/2020/12/Paneer-butter-masala-recipe-3-500x375.jpg',
  },
  {
    id: 34,
    name: 'पनीर मसाला',
    nameEn: 'Paneer Masala',
    price: 'Rs. 170',
    description: 'Paneer in spiced onion-tomato gravy',
    category: 'Paneer Special',
    image: 'https://indianfoods.co.in/wp-content/uploads/2024/02/paneer-tikka-masa-600x450.jpg',
  },
  {
    id: 35,
    name: 'पालक पनीर',
    nameEn: 'Palak Paneer',
    price: 'Rs. 170',
    description: 'Paneer in creamy spinach gravy',
    category: 'Paneer Special',
    image: 'https://i.pinimg.com/originals/3d/04/d0/3d04d008b34df3abe0f7a943c47d883c.jpg',
  },
  {
    id: 36,
    name: 'पनीर भुर्जी',
    nameEn: 'Paneer Bhurji',
    price: 'Rs. 220',
    description: 'Scrambled paneer with spices and onions',
    category: 'Paneer Special',
    image: 'https://tse1.mm.bing.net/th/id/OIP.oFzfpNoFJgP-1djVG_X-EQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  // Sides
  {
    id: 37,
    name: 'सलाद',
    nameEn: 'Salad',
    price: 'Rs. 60',
    description: 'Fresh salad',
    category: 'Sides',
    image: 'https://i.ytimg.com/vi/ZZsYgaFGB5E/maxresdefault.jpg',
  },
  {
    id: 38,
    name: 'दही',
    nameEn: 'Dahi',
    price: 'Rs. 60',
    description: 'Fresh curd',
    category: 'Sides',
    image: 'https://cookandsee.in/wp-content/uploads/2018/07/curd-1-750x515.jpg',
  },
  {
    id: 39,
    name: 'दही तडका',
    nameEn: 'Dahi Tadka',
    price: 'Rs. 110',
    description: 'Curd tempered with spices',
    category: 'Sides',
    image: 'https://i.ytimg.com/vi/3Zwdm6TXX4Q/maxresdefault.jpg',
  },
  // Roti
  {
    id: 40,
    name: 'रोटी',
    nameEn: 'Roti',
    price: 'Rs. 20',
    description: 'Whole wheat roti',
    category: 'Roti',
    image: 'https://cdn.mos.cms.futurecdn.net/z9yrzoMFd7hcFnvjzNjv5P.jpg',
  },
  {
    id: 41,
    name: 'घी रोटी',
    nameEn: 'Ghee Roti',
    price: 'Rs. 30',
    description: 'Roti brushed with ghee',
    category: 'Roti',
    image: 'https://i.pinimg.com/736x/cf/38/2e/cf382ef1b71efdadb829b643348cc52d.jpg',
  },
  {
    id: 42,
    name: 'भाकर',
    nameEn: 'Bhakar',
    price: 'Rs. 35',
    description: 'Jowar roti',
    category: 'Roti',
    image: 'https://img.freepik.com/premium-photo/sweet-roti-made-out-rice-flour-jaggery-ghee-gud-ki-roti-gur-ki-roti-jaggery-bhakri-meethi-gud-ki-roti-winter-food-copy-space_466689-81267.jpg',
  },
  {
    id: 43,
    name: 'घी भाकर',
    nameEn: 'Ghee Bhakar',
    price: 'Rs. 45',
    description: 'Jowar roti with ghee',
    category: 'Roti',
    image: 'https://img.freepik.com/premium-photo/sweet-roti-made-out-rice-flour-jaggery-ghee-gud-ki-roti-gur-ki-roti-jaggery-bhakri-meethi-gud-ki-roti-winter-food-copy-space_466689-81267.jpg',
  },
  {
    id: 44,
    name: 'भाकर ग्रेवी',
    nameEn: 'Bhakar Gravy',
    price: 'Rs. 120',
    description: 'Bhakar with gravy',
    category: 'Roti',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  // Rice
  {
    id: 45,
    name: 'साधा चावल',
    nameEn: 'Sadha Chawal',
    price: 'Rs. 120',
    description: 'Plain steamed rice',
    category: 'Rice',
    image: 'https://tse2.mm.bing.net/th/id/OIP.RxSAGm_MzAk0e2Sj-9LIaQAAAA?w=300&h=300&rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 46,
    name: 'जिरा फ्राय चावल',
    nameEn: 'Jira Fry Chawal',
    price: 'Rs. 140',
    description: 'Rice tempered with cumin',
    category: 'Rice',
    image: 'https://i.pinimg.com/736x/fd/ad/03/fdad03f17363536a0989eeaa78113928.jpg',
  },
  {
    id: 47,
    name: 'मसाला चावल',
    nameEn: 'Masala Chawal',
    price: 'Rs. 160',
    description: 'Spiced rice',
    category: 'Rice',
    image: 'https://th.bing.com/th/id/R.12653fdc5b8c3fd8baa09233a2fa0278?rik=8f8Y22k96eYNdQ&riu=http%3a%2f%2fhebbarskitchen.com%2fwp-content%2fuploads%2fmainPhotos%2fmasala-rice-recipe-vegetable-spiced-rice-spiced-rice-with-leftover-rice-2.jpeg&ehk=e2wZA5%2bxfUSiv5%2bCaoAao2QIoi%2bdcoRvrHwNH%2b8PSGg%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    id: 48,
    name: 'व्हेज पुलाव चावल',
    nameEn: 'Veg Pulao Chawal',
    price: 'Rs. 160',
    description: 'Vegetable pulao',
    category: 'Rice',
    image: 'https://i.pinimg.com/736x/be/f5/71/bef571d59b7ea0e74435e25ceeeb7d81.jpg',
  },
  {
    id: 49,
    name: 'पुलाव पनीर चावल',
    nameEn: 'Pulao Paneer Chawal',
    price: 'Rs. 180',
    description: 'Paneer pulao',
    category: 'Rice',
    image: 'https://manjulaskitchen.com/wp-content/uploads/paneer_pulao.jpg',
  },
  {
    id: 50,
    name: 'खिचडी चावल',
    nameEn: 'Khichdi Chawal',
    price: 'Rs. 160',
    description: 'Rice and lentil khichdi',
    category: 'Rice',
    image: 'https://tse4.mm.bing.net/th/id/OIP.wblvAHjIIPB-C_zk8h7SMgHaGE?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  // Beverages
  {
    id: 51,
    name: 'ताक',
    nameEn: 'Taak',
    price: 'Rs. 20',
    description: 'Spiced buttermilk',
    category: 'Beverages',
    image: 'https://tse1.mm.bing.net/th/id/OIP.QJSAGyjuuxtKLNQlgE-dDwHaFX?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 52,
    name: 'लस्सी',
    nameEn: 'Lassi',
    price: 'Rs. 30',
    description: 'Fresh sweet lassi',
    category: 'Beverages',
    image: 'https://thumbs.dreamstime.com/b/masala-buttermilk-drink-chaas-made-yogurt-served-glass-over-rustic-wooden-background-refreshing-summer-days-223998722.jpg',
  },
]

export const FEATURES = [
  {
    id: 1,
    icon: 'leaf',
    title: 'Pure Vegetarian',
    description: '100% pure veg food prepared with fresh & quality ingredients.',
  },
  {
    id: 2,
    icon: 'tree',
    title: 'Nature View Dining',
    description: 'Enjoy your meals with the comfort of greenery and open surroundings.',
  },
  {
    id: 3,
    icon: 'chef',
    title: 'Hygienic Kitchen',
    description: 'Clean, hygienic and well maintained kitchen for your safety.',
  },
  {
    id: 4,
    icon: 'family',
    title: 'Family Friendly',
    description: 'A perfect place for family dining, friends & group gatherings.',
  },
  {
    id: 5,
    icon: 'service',
    title: 'Fast & Friendly Service',
    description: 'Quick service with a smile to make your experience even better.',
  },
  {
    id: 6,
    icon: 'parking',
    title: 'Ample Parking',
    description: 'Spacious and secure parking for cars, bikes and buses.',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Swanand Hatwar',
    rating: 5,
    text: 'Amazing food, beautiful ambience and super location. A must visit place on Nagpur Highway!',
    avatar: '',
  },
  {
    id: 2,
    name: 'Vaishnavi',
    rating: 5,
    text: 'Very clean, pure veg and the view is just wow! Perfect for family dining dinner.',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: 3,
    name: 'Amit K.',
    rating: 5,
    text: 'Best dhaba experience ever. Food quality and service are excellent. Will visit again!',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 4,
    name: 'Priya M.',
    rating: 5,
    text: 'The paneer Masala is absolutely divine. Warm hospitality and peaceful environment.',
    avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
]

export const GALLERY_IMAGES = [
  {
    id: 1,
    src: '/gallery/pic_1.png',
    alt: 'Restaurant outdoor dining',
    category: 'Ambience',
  },
  {
    id: 2,
    src: '/gallery/pic_2.png',
    alt: 'Warm evening lights',
    category: 'Ambience',
  },
  {
    id: 3,
    src: '/gallery/pic_3.png',
    alt: 'A glimpse of the greenery',
    category: 'Ambience',
  },
  {
    id: 4,
    src: '/gallery/pic_4.png',
    alt: 'Amazing Views',
    category: 'Ambience',
  },
]
