export const SITE_NAME = 'Hotel Vatika Dhaba'
export const TAGLINE = 'Premium Pure Veg Dining with a Nature View'

export const CONTACT = {
  address: 'Hotel Vatika Dhaba\nNagpur Highway, Maharashtra, India',
  phone: '+91 9890836578',
  whatsapp: '9890836578',
  hours: '11:00 AM - 11:00 PM',
  mapsUrl: 'https://maps.app.goo.gl/X67CyikEynoZ967s5',
  mapsEmbed: 'https://www.google.com/maps?q=Hotel%20Vatika%20Dhaba%20Nagpur%20Highway&output=embed',
}

export const NAV_LINKS = [
  { label: 'Home', href: '#home' },
  { label: 'Menu', href: '#menu' },
  { label: 'Gallery', href: '#gallery' },
  { label: 'Contact', href: '#contact' },
]

export const MENU_CATEGORIES = ['All', 'Starters', 'Parathas', 'Dal', 'Sabzi', 'Paneer Special', 'Sides', 'Breads', 'Rice', 'Beverages']

export const DISHES = [
  // Starters
  {
    id: 1,
    name: 'पापड साधा',
    nameEn: 'Papad Sadha',
    price: 'Rs. 10',
    description: 'Crispy papad',
    category: 'Starters',
    image: 'https://images.pexels.com/photos/34739831/pexels-photo-34739831.jpeg?cs=srgb&dl=pexels-drmkhawarnazir-34739831.jpg&fm=jpg',
  },
  {
    id: 2,
    name: 'पापड मसाला',
    nameEn: 'Papad Masala',
    price: 'Rs. 20',
    description: 'Papad topped with spices',
    category: 'Starters',
    image: 'https://images.pexels.com/photos/34347890/pexels-photo-34347890.jpeg?cs=srgb&dl=pexels-shyamsrivastava-34347890.jpg&fm=jpg',
  },
  {
    id: 3,
    name: 'पापड भुर्जी',
    nameEn: 'Papad Bhurji',
    price: 'Rs. 100',
    description: 'Crispy crushed papad with onions and spices',
    category: 'Starters',
    image: 'https://images.pexels.com/photos/34347890/pexels-photo-34347890.jpeg?cs=srgb&dl=pexels-shyamsrivastava-34347890.jpg&fm=jpg',
  },
  {
    id: 4,
    name: 'कांदा पकोडा',
    nameEn: 'Kanda Pakoda',
    price: 'Rs. 80',
    description: 'Crispy onion fritters',
    category: 'Starters',
    image: 'https://unsplash.com/photos/inz8vyeEumY/download?force=true',
  },
  {
    id: 5,
    name: 'पनीर पकोडा',
    nameEn: 'Paneer Pakoda',
    price: 'Rs. 100',
    description: 'Crispy paneer fritters',
    category: 'Starters',
    image: 'https://images.pexels.com/photos/8585763/pexels-photo-8585763.jpeg?cs=srgb&dl=pexels-mukesh-kumar-76103954-8585763.jpg&fm=jpg',
  },
  // Parathas
  {
    id: 6,
    name: 'पराठा साधा',
    nameEn: 'Paratha Sadha',
    price: 'Rs. 50',
    description: 'Plain paratha',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/36704398/pexels-photo-36704398.jpeg?cs=srgb&dl=pexels-amjad-ali-2159823888-36704398.jpg&fm=jpg',
  },
  {
    id: 7,
    name: 'पराठा मसाला',
    nameEn: 'Paratha Masala',
    price: 'Rs. 80',
    description: 'Spiced paratha',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/33428723/pexels-photo-33428723.jpeg?cs=srgb&dl=pexels-shootsaga-33428723.jpg&fm=jpg',
  },
  {
    id: 8,
    name: 'पराठा मसाला (घी)',
    nameEn: 'Paratha Masala (Ghee)',
    price: 'Rs. 100',
    description: 'Spiced paratha with ghee',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/35079286/pexels-photo-35079286.jpeg?cs=srgb&dl=pexels-drmkhawarnazir-35079286.jpg&fm=jpg',
  },
  {
    id: 9,
    name: 'पराठा पनीर',
    nameEn: 'Paratha Paneer',
    price: 'Rs. 100',
    description: 'Paneer stuffed paratha',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/12737919/pexels-photo-12737919.jpeg?cs=srgb&dl=pexels-dhiraj-jain-207743066-12737919.jpg&fm=jpg',
  },
  {
    id: 10,
    name: 'पराठा पनीर (घी)',
    nameEn: 'Paratha Paneer (Ghee)',
    price: 'Rs. 120',
    description: 'Paneer stuffed paratha with ghee',
    category: 'Parathas',
    image: 'https://images.pexels.com/photos/28885201/pexels-photo-28885201.jpeg?cs=srgb&dl=pexels-vladimir-waikar-1959075778-28885201.jpg&fm=jpg',
  },
  // Dal
  {
    id: 11,
    name: 'दाल तडका',
    nameEn: 'Dal Tadka',
    price: 'Rs. 150',
    description: 'Yellow dal tempered with desi ghee and cumin',
    category: 'Dal',
    image: 'https://images.pexels.com/photos/33379362/pexels-photo-33379362.jpeg?cs=srgb&dl=pexels-masuma-rahaman-437541976-33379362.jpg&fm=jpg',
  },
  {
    id: 12,
    name: 'दाल फ्राय',
    nameEn: 'Dal Fry',
    price: 'Rs. 140',
    description: 'Lightly tempered yellow dal',
    category: 'Dal',
    image: 'https://images.pexels.com/photos/28675074/pexels-photo-28675074.jpeg?cs=srgb&dl=pexels-kunal-lakhotia-781256899-28675074.jpg&fm=jpg',
  },
  {
    id: 13,
    name: 'उळदचना दाल',
    nameEn: 'Uladchana Dal',
    price: 'Rs. 140',
    description: 'Split black gram dal',
    category: 'Dal',
    image: 'https://images.pexels.com/photos/37182514/pexels-photo-37182514.jpeg?cs=srgb&dl=pexels-drmkhawarnazir-37182514.jpg&fm=jpg',
  },
  {
    id: 14,
    name: 'दाल मकनी',
    nameEn: 'Dal Makhani',
    price: 'Rs. 190',
    description: 'Creamy black lentils slow-cooked with butter',
    category: 'Dal',
    image: 'https://images.pexels.com/photos/28674555/pexels-photo-28674555.jpeg?cs=srgb&dl=pexels-kunal-lakhotia-781256899-28674555.jpg&fm=jpg',
  },
  // Sabzi
  {
    id: 15,
    name: 'आलू मटर',
    nameEn: 'Aloo Matar',
    price: 'Rs. 140',
    description: 'Potato and peas curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/33643313/pexels-photo-33643313.jpeg?cs=srgb&dl=pexels-pinaki-panda-3019803-33643313.jpg&fm=jpg',
  },
  {
    id: 16,
    name: 'गोबी मसाला',
    nameEn: 'Gobi Masala',
    price: 'Rs. 140',
    description: 'Cauliflower in spiced gravy',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/35071824/pexels-photo-35071824.jpeg?cs=srgb&dl=pexels-miltonphotography-35071824.jpg&fm=jpg',
  },
  {
    id: 17,
    name: 'भेंडी फ्राय',
    nameEn: 'Bhindi Fry',
    price: 'Rs. 140',
    description: 'Crispy okra fry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/35008222/pexels-photo-35008222.jpeg?cs=srgb&dl=pexels-rajani33-3567470-35008222.jpg&fm=jpg',
  },
  {
    id: 18,
    name: 'राजमा',
    nameEn: 'Rajma',
    price: 'Rs. 140',
    description: 'Kidney beans curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/12737912/pexels-photo-12737912.jpeg?cs=srgb&dl=pexels-dhiraj-jain-207743066-12737912.jpg&fm=jpg',
  },
  {
    id: 19,
    name: 'चना मसाला',
    nameEn: 'Chana Masala',
    price: 'Rs. 140',
    description: 'Spiced chickpea curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/29066704/pexels-photo-29066704.jpeg?cs=srgb&dl=pexels-sabyasachi-das-45419624-29066704.jpg&fm=jpg',
  },
  {
    id: 20,
    name: 'मटकी',
    nameEn: 'Matki',
    price: 'Rs. 140',
    description: 'Sprouted moth beans curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/8479384/pexels-photo-8479384.jpeg?cs=srgb&dl=pexels-anntarazevich-8479384.jpg&fm=jpg',
  },
  {
    id: 21,
    name: 'कळी पकोडा',
    nameEn: 'Kali Pakoda',
    price: 'Rs. 140',
    description: 'Crispy gram flour fritters',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/33104648/pexels-photo-33104648.jpeg?cs=srgb&dl=pexels-pinaki-panda-3019803-33104648.jpg&fm=jpg',
  },
  {
    id: 22,
    name: 'शेव भाजी',
    nameEn: 'Shev Bhaji',
    price: 'Rs. 140',
    description: 'Sev in vegetable curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/20408461/pexels-photo-20408461.jpeg?cs=srgb&dl=pexels-jack-baghel-2199968-20408461.jpg&fm=jpg',
  },
  {
    id: 23,
    name: 'आलू जिरा',
    nameEn: 'Aloo Jira',
    price: 'Rs. 140',
    description: 'Potato tempered with cumin',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/33643313/pexels-photo-33643313.jpeg?cs=srgb&dl=pexels-pinaki-panda-3019803-33643313.jpg&fm=jpg',
  },
  {
    id: 24,
    name: 'टमाटर चटणी',
    nameEn: 'Tomato Chutney',
    price: 'Rs. 140',
    description: 'Spicy tomato chutney',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/17424800/pexels-photo-17424800.jpeg?cs=srgb&dl=pexels-lunarly-83082820-17424800.jpg&fm=jpg',
  },
  {
    id: 25,
    name: 'बैंगन भरता',
    nameEn: 'Baingan Bharta',
    price: 'Rs. 140',
    description: 'Smoked eggplant mash',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/36458544/pexels-photo-36458544.jpeg?cs=srgb&dl=pexels-drmkhawarnazir-36458544.jpg&fm=jpg',
  },
  {
    id: 26,
    name: 'झुणका',
    nameEn: 'Zunka',
    price: 'Rs. 140',
    description: 'Traditional Maharashtrian gram flour curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/37420999/pexels-photo-37420999.jpeg?cs=srgb&dl=pexels-kunal-lakhotia-781256899-37420999.jpg&fm=jpg',
  },
  {
    id: 27,
    name: 'मेथी फ्राय',
    nameEn: 'Methi Fry',
    price: 'Rs. 140',
    description: 'Fenugreek leaves fry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/13513758/pexels-photo-13513758.jpeg?cs=srgb&dl=pexels-sagar-konduri-298000195-13513758.jpg&fm=jpg',
  },
  {
    id: 28,
    name: 'करेला फ्राय',
    nameEn: 'Karela Fry',
    price: 'Rs. 140',
    description: 'Bitter gourd fry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/13569982/pexels-photo-13569982.jpeg?cs=srgb&dl=pexels-davide-nunziata-312594342-13569982.jpg&fm=jpg',
  },
  {
    id: 29,
    name: 'पालक प्लेन',
    nameEn: 'Palak Plain',
    price: 'Rs. 150',
    description: 'Plain spinach curry',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/8625813/pexels-photo-8625813.jpeg?cs=srgb&dl=pexels-pranjall-kumar-150768-8625813.jpg&fm=jpg',
  },
  {
    id: 30,
    name: 'ग्रेवी आलू',
    nameEn: 'Gravy Aloo',
    price: 'Rs. 150',
    description: 'Potato in rich gravy',
    category: 'Sabzi',
    image: 'https://images.pexels.com/photos/33643298/pexels-photo-33643298.jpeg?cs=srgb&dl=pexels-pinaki-panda-3019803-33643298.jpg&fm=jpg',
  },
  {
    id: 31,
    name: 'मिक्स व्हेज',
    nameEn: 'Mix Veg',
    price: 'Rs. 160',
    description: 'Seasonal vegetables in spiced tomato gravy',
    category: 'Sabzi',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  // Paneer Special
  {
    id: 32,
    name: 'पनीर मेथी फ्राय',
    nameEn: 'Paneer Methi Fry',
    price: 'Rs. 200',
    description: 'Paneer with fenugreek leaves',
    category: 'Paneer Special',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 33,
    name: 'पनीर बटर मसाला',
    nameEn: 'Paneer Butter Masala',
    price: 'Rs. 200',
    description: 'Paneer in rich buttery tomato gravy',
    category: 'Paneer Special',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 34,
    name: 'पनीर मसाला',
    nameEn: 'Paneer Masala',
    price: 'Rs. 170',
    description: 'Paneer in spiced onion-tomato gravy',
    category: 'Paneer Special',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 35,
    name: 'पालक पनीर',
    nameEn: 'Palak Paneer',
    price: 'Rs. 170',
    description: 'Paneer in creamy spinach gravy',
    category: 'Paneer Special',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 36,
    name: 'पनीर भुर्जी',
    nameEn: 'Paneer Bhurji',
    price: 'Rs. 220',
    description: 'Scrambled paneer with spices and onions',
    category: 'Paneer Special',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  // Sides
  {
    id: 37,
    name: 'सलाद',
    nameEn: 'Salad',
    price: 'Rs. 60',
    description: 'Fresh salad',
    category: 'Sides',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 38,
    name: 'दही',
    nameEn: 'Dahi',
    price: 'Rs. 60',
    description: 'Fresh curd',
    category: 'Sides',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 39,
    name: 'दही तडका',
    nameEn: 'Dahi Tadka',
    price: 'Rs. 110',
    description: 'Curd tempered with spices',
    category: 'Sides',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  // Breads
  {
    id: 40,
    name: 'रोटी',
    nameEn: 'Roti',
    price: 'Rs. 20',
    description: 'Whole wheat roti',
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 41,
    name: 'घी रोटी',
    nameEn: 'Ghee Roti',
    price: 'Rs. 30',
    description: 'Roti brushed with ghee',
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 42,
    name: 'भाकर',
    nameEn: 'Bhakar',
    price: 'Rs. 35',
    description: 'Jowar roti',
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 43,
    name: 'घी भाकर',
    nameEn: 'Ghee Bhakar',
    price: 'Rs. 45',
    description: 'Jowar roti with ghee',
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 44,
    name: 'भाकर ग्रेवी',
    nameEn: 'Bhakar Gravy',
    price: 'Rs. 120',
    description: 'Bhakar with gravy',
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  // Rice
  {
    id: 45,
    name: 'साधा चावल',
    nameEn: 'Sadha Chawal',
    price: 'Rs. 120',
    description: 'Plain steamed rice',
    category: 'Rice',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9aef0805?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 46,
    name: 'जिरा फ्राय चावल',
    nameEn: 'Jira Fry Chawal',
    price: 'Rs. 140',
    description: 'Rice tempered with cumin',
    category: 'Rice',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/jeera-rice-recipe.jpg',
  },
  {
    id: 47,
    name: 'मसाला चावल',
    nameEn: 'Masala Chawal',
    price: 'Rs. 160',
    description: 'Spiced rice',
    category: 'Rice',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/masala-rice-recipe.jpg',
  },
  {
    id: 48,
    name: 'व्हेज पुलाव चावल',
    nameEn: 'Veg Pulao Chawal',
    price: 'Rs. 160',
    description: 'Vegetable pulao',
    category: 'Rice',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/veg-pulao-recipe.jpg',
  },
  {
    id: 49,
    name: 'पुलाव पनीर चावल',
    nameEn: 'Pulao Paneer Chawal',
    price: 'Rs. 180',
    description: 'Paneer pulao',
    category: 'Rice',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/paneer-pulao-recipe.jpg',
  },
  {
    id: 50,
    name: 'खिचडी चावल',
    nameEn: 'Khichdi Chawal',
    price: 'Rs. 160',
    description: 'Rice and lentil khichdi',
    category: 'Rice',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/khichdi-recipe.jpg',
  },
  // Beverages
  {
    id: 51,
    name: 'ताक',
    nameEn: 'Taak',
    price: 'Rs. 20',
    description: 'Spiced buttermilk',
    category: 'Beverages',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/taak-recipe.jpg',
  },
  {
    id: 52,
    name: 'लस्सी',
    nameEn: 'Lassi',
    price: 'Rs. 30',
    description: 'Fresh sweet lassi',
    category: 'Beverages',
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/11/lassi-recipe.jpg',
  },
]

export const FEATURES = [
  {
    id: 1,
    icon: 'leaf',
    title: 'Pure Vegetarian',
    description: '100% pure veg food prepared with fresh & quality ingredients.',
  },
  {
    id: 2,
    icon: 'tree',
    title: 'Nature View Dining',
    description: 'Enjoy your meals with the comfort of greenery and open surroundings.',
  },
  {
    id: 3,
    icon: 'chef',
    title: 'Hygienic Kitchen',
    description: 'Clean, hygienic and well maintained kitchen for your safety.',
  },
  {
    id: 4,
    icon: 'family',
    title: 'Family Friendly',
    description: 'A perfect place for family dining, friends & group gatherings.',
  },
  {
    id: 5,
    icon: 'service',
    title: 'Fast & Friendly Service',
    description: 'Quick service with a smile to make your experience even better.',
  },
  {
    id: 6,
    icon: 'parking',
    title: 'Ample Parking',
    description: 'Spacious and secure parking for cars, bikes and buses.',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Swanand Hatwar',
    rating: 5,
    text: 'Amazing food, beautiful ambience and super location. A must visit place on Nagpur Highway!',
    avatar: '',
  },
  {
    id: 2,
    name: 'Vaishnavi',
    rating: 5,
    text: 'Very clean, pure veg and the view is just wow! Perfect for family dining dinner.',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: 3,
    name: 'Amit K.',
    rating: 5,
    text: 'Best dhaba experience ever. Food quality and service are excellent. Will visit again!',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 4,
    name: 'Priya M.',
    rating: 5,
    text: 'The paneer Masala is absolutely divine. Warm hospitality and peaceful environment.',
    avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
]

export const GALLERY_IMAGES = [
  {
    id: 1,
    src: '/gallery/pic_1.png',
    alt: 'Restaurant outdoor dining',
    category: 'Ambience',
  },
  {
    id: 2,
    src: '/gallery/pic_2.png',
    alt: 'Warm evening lights',
    category: 'Ambience',
  },
  {
    id: 3,
    src: '/gallery/pic_3.png',
    alt: 'A glimpse of the greenery',
    category: 'Ambience',
  },
  {
    id: 4,
    src: '/gallery/pic_4.png',
    alt: 'Amazing Views',
    category: 'Ambience',
  },
]
